export const products = {
    trainingShort: {
      name: "The Training Short",
      price: 23.99,
      shortDescription: "Two layers in one. The inner covers past the knee — train without thinking about it.",
      description: "Two layers in one short. The outer sits above the knee, the inner covers past it — so you're covered whether you're squatting, sprinting, or making sujood.",
      href: "/shop/training-short",
      colours: [
        { name: "Black", image: "/product-black.png" },
        { name: "Navy", image: "/product-navy-blue.png" },
        { name: "Olive", image: "/product-olive-green.png" },
      ],
      details: [
        "Two layers, one short",
        "Outer shell sits above the knee",
        "Inner layer extends to the knee",
        "Lightweight moisture-wicking fabric",
        "87% Polyester, 13% Elastane",
        "Machine washable",
      ],
    },
    underlayer: {
      name: "The Underlayer",
      price: 11.99,
      shortDescription: "The inner layer on its own. Knee length — wear it under any shorts you already own",
      description: "Just the inner layer. Knee length, made to go under any shorts you already own — the gym, the mall, anywhere.",
      href: "/shop/underlayer",
      image: "/underlayer-black.png",
      details: [
        "Knee length coverage",
        "Wear under any shorts",
        "Lightweight and breathable",
        "Suitable for everyday wear",
        "87% Polyester, 13% Elastane",
        "Machine washable",
      ],
    },
    thermal: {
      name: "The Thermal",
      price: 14.99,
      shortDescription: "Ankle length thermal base layer for winter training. Full coverage, moisture wicking warmth.",
      description: "Ankle length thermal base layer for winter training. Full leg coverage, moisture wicking warmth — built for the cold without compromising your deen.",
      href: "/shop/thermal",
      image: "/thermal-black.png",
      details: [
        "Ankle length full coverage",
        "Thermal base layer for winter",
        "Moisture wicking and warm",
        "Wear under any shorts or trousers",
        "87% Polyester, 13% Elastane",
        "Machine washable",
      ],
    },
  }